name: DevOps Practice Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show files
        run: ls

      - name: Simulate build
        run: echo "Building application..."

      - name: Simulate test
        run: echo "Running tests..."
